version: "3.3"
services:
    web:
        build:
            context: .
        ports:
            - "5000:80"
        depends_on:
            - sqldata    
        
    sqldata:
        image: "mcr.microsoft.com/mssql/server"
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
         
        